trigger:
- main

stages:
  - stage: Local
    dependsOn: []
    jobs:

      - job: Ubuntu2004_gcc9
        displayName: Ubuntu 20.04 - gcc-9
        timeoutInMinutes: 15
        condition: False
        pool:
          vmImage: 'ubuntu-20.04'
        variables:
          CC: gcc-9
          CXX: g++-9
          BUILD_DIRECTORY: $(Build.SourcesDirectory)/build
        steps:
          - task: CmdLine@2
            displayName: 'Install Build Tools'
            inputs:
              script: |
                sudo apt update -y
                sudo apt install -y --no-install-recommends make cmake ninja-build python3.8 pip
                sudo pip install conan
          - task: CmdLine@2
            displayName: 'Create Build Folder'
            inputs:
              script: mkdir build
              workingDirectory: $(Build.SourcesDirectory)
          - task: CmdLine@2
            displayName: 'Configure'
            inputs:
              script: cmake -G Ninja -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) .. 
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Build'
            inputs:
              script: cmake --build . --config $(BUILD_TYPE)
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Unit Test'
            continueOnError: true
            inputs:
              script: 'ctest . --build-config $(BUILD_TYPE) --output-on-failure --timeout 60 -T Test -VV -j10'
              workingDirectory: $(BUILD_DIRECTORY)
          - task: PublishTestResults@2
            displayName: 'Publish Results'
            continueOnError: true
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '$(BUILD_DIRECTORY)/Testing/*/Test.xml'
              testRunTitle: 'Test Results - gcc-9'

      - job: Ubuntu2004_clang10
        displayName: Ubuntu 20.04 - clang-10
        condition: False
        timeoutInMinutes: 15
        pool:
          vmImage: 'ubuntu-20.04'
        variables:
          CC: clang-10
          CXX: clang++-10
          BUILD_DIRECTORY: $(Build.SourcesDirectory)/build
        steps:
          - task: CmdLine@2
            displayName: 'Install Build Tools'
            inputs:
              script: |
                sudo apt update -y
                sudo apt install -y --no-install-recommends make cmake ninja-build python3.8 pip
                sudo pip install conan
          - task: CmdLine@2
            displayName: 'Create Build Folder'
            inputs:
              script: mkdir build
              workingDirectory: $(Build.SourcesDirectory)
          - task: CmdLine@2
            displayName: 'Configure'
            inputs:
              script: cmake -G Ninja -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) .. 
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Build'
            inputs:
              script: cmake --build . --config $(BUILD_TYPE)
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Unit Test'
            continueOnError: true
            inputs:
              script: 'ctest . --build-config $(BUILD_TYPE) --output-on-failure --timeout 60 -T Test -VV -j10'
              workingDirectory: $(BUILD_DIRECTORY)
          - task: PublishTestResults@2
            displayName: 'Publish Results'
            continueOnError: true
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '$(BUILD_DIRECTORY)/Testing/*/Test.xml'
              testRunTitle: 'Test Results - clang-10'

      - job: Windows2019_msvc2019
        displayName: Windows 2019 - msvc-2019
        timeoutInMinutes: 15
        pool:
          vmImage: 'windows-2019'
        variables:
          BUILD_DIRECTORY: $(Build.SourcesDirectory)/build
          MSVC_DEV_ENV: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat"
        steps:
          - task: CmdLine@2
            displayName: 'Install Build Tools'
            inputs:
              script: |
                choco install --accept-license -y Ninja
                pip install conan
          - task: CmdLine@2
            displayName: 'Create Build Folder'
            inputs:
              script: mkdir build
              workingDirectory: $(Build.SourcesDirectory)
          - task: CmdLine@2
            displayName: 'Configure'
            inputs:
              script: |
                call "$(MSVC_DEV_ENV)" -arch=amd64 -host_arch=amd64
                cmake -G Ninja -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) .. 
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Build'
            inputs:
              script: cmake --build . --config $(BUILD_TYPE)
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Unit Test'
            continueOnError: true
            inputs:
              script: ctest . --build-config $(BUILD_TYPE) --output-on-failure --timeout 60 -T Test -VV -j10
              workingDirectory: $(BUILD_DIRECTORY)
          - task: PublishTestResults@2
            displayName: 'Publish test results'
            continueOnError: true
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '$(BUILD_DIRECTORY)/Testing/*/Test.xml'
              testRunTitle: 'Test Results - msvc-2019'

      - job: MacOS1015_clang10
        displayName: MacOS 1015 - clang-10
        timeoutInMinutes: 15
        pool:
          vmImage: 'macOS-10.15'
        variables:
          BUILD_DIRECTORY: $(Build.SourcesDirectory)/build
        steps:
          - task: CmdLine@2
            displayName: 'Install Build Tools'
            inputs:
              script: |
                brew install ninja
                pipx install conan
          - task: CmdLine@2
            displayName: 'Create Build Folder'
            inputs:
              script: mkdir build
              workingDirectory: $(Build.SourcesDirectory)
          - task: CmdLine@2
            displayName: 'Configure'
            inputs:
              script: cmake -G Ninja -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) .. 
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Build'
            inputs:
              script: cmake --build . --config $(BUILD_TYPE)
              workingDirectory: $(BUILD_DIRECTORY)
          - task: CmdLine@2
            displayName: 'Unit Test'
            continueOnError: true
            inputs:
              script: 'ctest . --build-config $(BUILD_TYPE) --output-on-failure --timeout 60 -T Test -VV -j10'
              workingDirectory: $(BUILD_DIRECTORY)
          - task: PublishTestResults@2
            displayName: 'Publish Results'
            continueOnError: true
            inputs:
              testResultsFormat: 'cTest'
              testResultsFiles: '$(BUILD_DIRECTORY)/Testing/*/Test.xml'
              testRunTitle: 'Test Results - MacOS - clang-10'


  - stage: Container
    dependsOn: []
    condition: False
    jobs:

      - job: Docker_gcc9
        displayName: Docker - gcc-9
        timeoutInMinutes: 15
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - task: CmdLine@2
            displayName: 'Build Unit Test'
            inputs:
              script: docker build -f docker/Dockerfile.gcc --rm -t dkpp_test:gcc --target test .
          - task: CmdLine@2
            displayName: 'Run Unit Test'
            inputs:
              script: docker run --rm --name docker_cpp_test_gcc dkpp_test:gcc
          - task: CmdLine@2
            displayName: 'Build App'
            inputs:
              script: docker build -f docker/Dockerfile.gcc --rm -t dkpp:gcc .
          - task: CmdLine@2
            displayName: 'Run App'
            inputs:
              script: docker run --rm --name docker_cpp_gcc dkpp:gcc

      - job: Docker_clang10
        displayName: Docker - clang-10
        timeoutInMinutes: 15
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - task: CmdLine@2
            displayName: 'Build Unit Test'
            inputs:
              script: docker build -f docker/Dockerfile.clang --rm -t dkpp_test:clang --target test .
          - task: CmdLine@2
            displayName: 'Run Unit Test'
            inputs:
              script: docker run --rm --name docker_cpp_test_clang dkpp_test:clang
          - task: CmdLine@2
            displayName: 'Build App'
            inputs:
              script: docker build -f docker/Dockerfile.clang --rm -t dkpp:clang .
          - task: CmdLine@2
            displayName: 'Run App'
            inputs:
              script: docker run --rm --name docker_cpp_clang dkpp:clang
          
